CREATE TABLE USERS (
  ID INT PRIMARY KEY,
  NAME VARCHAR2(30) NOT NULL,
  EMAIL VARCHAR2(100) UNIQUE,
  PASSWORD VARCHAR2(100)
);

CREATE TABLE POSTS (
  ID INT PRIMARY KEY,
  TITLE VARCHAR2(30) NOT NULL,
  BODY VARCHAR2(1000) NOT NULL,

  AUTHOR_ID REFERENCES USERS(ID)
);

CREATE SEQUENCE USER_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POSTS_ID_SEQ START WITH 1 INCREMENT BY 1;

INSERT INTO USERS
VALUES(USER_ID_SEQ.nextval, 'anthony ribeiro', 'anthony@email.com', '123123123');

INSERT INTO POSTS VALUES(POSTS_ID_SEQ.nextval, '1 Post', 'Conteúdo do post 1', 1);
INSERT INTO POSTS VALUES(POSTS_ID_SEQ.nextval, '2 Post', 'Conteúdo do post 2', 1);
INSERT INTO POSTS VALUES(POSTS_ID_SEQ.nextval, '3 Post', 'Conteúdo do post 3', 1);

SELECT * FROM USERS;
SELECT * FROM POSTS;

SELECT * FROM POSTS WHERE ID = 1;
SELECT * FROM POSTS WHERE ID = 2;
SELECT * FROM POSTS WHERE ID = 3;

UPDATE POSTS SET BODY = 'NEW CONTENT FOR POST 3' WHERE ID = 3;

DELETE FROM POSTS WHERE ID = 3;